# Generated by Django 5.1.4 on 2025-08-07 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeditationLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='meditation_library/', verbose_name='Image')),
                ('file', models.FileField(blank=True, null=True, upload_to='meditation_library/', verbose_name='File')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Meditation Library',
                'verbose_name_plural': '4. Meditation Libraries',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Name')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Price')),
                ('is_monthly', models.BooleanField(blank=True, default=True, null=True, verbose_name='Monthly Plan')),
                ('is_annual', models.BooleanField(blank=True, default=False, null=True, verbose_name='Annual Plan')),
                ('is_free_trial', models.BooleanField(blank=True, default=False, null=True, verbose_name='Free Trial')),
                ('discount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': '5. Plans',
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(max_length=50, verbose_name='Notification Type')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is Sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Push Notification',
                'verbose_name_plural': '8. Push Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rituals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ritual Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ritual_type', models.CharField(choices=[('guided', 'Guided'), ('story', 'Story')], default='guided', max_length=50, verbose_name='Ritual Type')),
                ('tone', models.CharField(choices=[('dreamy', 'Dreamy'), ('asmr', 'ASMR')], max_length=50, verbose_name='Choose your tone')),
                ('voice', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Choose your voice')),
                ('duration', models.CharField(choices=[('2', '2 min'), ('5', '5 min'), ('10', '10 min')], default='5', max_length=10, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ritual',
                'verbose_name_plural': 'Rituals',
            },
        ),
        migrations.CreateModel(
            name='RitualType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ritual Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ritual Type',
                'verbose_name_plural': '2. Ritual Types',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('is_agree', models.BooleanField(blank=True, default=False, null=True, verbose_name='Agreement to Terms')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.group', verbose_name='Groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_set', to='auth.permission', verbose_name='User Permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': '1. Users',
            },
        ),
        migrations.CreateModel(
            name='CustomUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.TextField(blank=True, null=True, verbose_name='Tell me about your dream life')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Specific goals')),
                ('age_range', models.CharField(blank=True, max_length=20, null=True, verbose_name='Age Range')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('happiness', models.TextField(blank=True, null=True, verbose_name='What Makes You Happy?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
            },
        ),
        migrations.CreateModel(
            name='MeditationGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='meditations/', verbose_name='File')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ritual', to='accounts.rituals', verbose_name='Customize Ritual')),
                ('ritual_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ritual_type', to='accounts.ritualtype', verbose_name='Ritual Type')),
            ],
            options={
                'verbose_name': 'Meditation',
                'verbose_name_plural': '3. Meditations',
            },
        ),
        migrations.CreateModel(
            name='LikeMeditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_meditation', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_meditation', to='accounts.meditationgenerate', verbose_name='Meditation')),
            ],
            options={
                'verbose_name': 'Like Meditation',
                'verbose_name_plural': 'Like Meditations',
            },
        ),
        migrations.CreateModel(
            name='PlanDescriptin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_description', to='accounts.plans', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Description',
                'verbose_name_plural': 'Plan Descriptions',
            },
        ),
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_choice', models.CharField(blank=True, choices=[('struggling', 'Struggling'), ('neutral', 'Neutral'), ('excellent', 'Excellent')], max_length=10, null=True, verbose_name='Check In Choice')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('check_in_date', models.DateField(auto_now_add=True, verbose_name='Check In Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Check In',
                'verbose_name_plural': 'User Check Ins',
            },
        ),
        migrations.CreateModel(
            name='UserLifeVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('vision_type', models.CharField(choices=[('life_vision', 'Life Vision'), ('goal', 'Goal'), ('dream', 'Dream'), ('north_star', 'North Star')], default='life_vision', max_length=20, verbose_name='Vision Type')),
                ('goal_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_started', 'Not Started'), ('paused', 'Paused')], default='not_started', max_length=20, verbose_name='Goal Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_visions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Life Vision',
                'verbose_name_plural': '7. User Life Visions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=500, verbose_name='Device Token')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=20, verbose_name='Device Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Device Token',
                'verbose_name_plural': '9. User Device Tokens',
                'unique_together': {('user', 'device_token')},
            },
        ),
        migrations.CreateModel(
            name='UserLoginTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True, verbose_name='Login Date')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Login Tracker',
                'verbose_name_plural': '6. User Login Trackers',
                'unique_together': {('user', 'login_date')},
            },
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='accounts.plans', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Plan',
                'verbose_name_plural': 'User Plans',
                'unique_together': {('user', 'plan')},
            },
        ),
    ]
