# Generated by Django 5.1.4 on 2025-07-05 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Plan Name')),
                ('price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Price')),
                ('description', models.JSONField(blank=True, null=True, verbose_name='Description')),
                ('is_monthly', models.BooleanField(blank=True, default=True, null=True, verbose_name='Monthly Plan')),
                ('is_annual', models.BooleanField(blank=True, default=False, null=True, verbose_name='Annual Plan')),
                ('discount', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='Rituals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ritual Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ritual_type', models.CharField(choices=[('guided_meditations', 'Guided meditations'), ('breathing_exercises', 'Breathing exercises'), ('sleep_stories', 'Sleep stories'), ('nature_sounds', 'Nature sounds'), ('music_therapy', 'Music therapy')], default='guided_meditations', max_length=50, verbose_name='Ritual Type')),
                ('tone', models.CharField(choices=[('dreamy', 'Dreamy'), ('calming', 'Calming'), ('energizing', 'Energizing'), ('peaceful', 'Peaceful'), ('focused', 'Focused')], default='calming', max_length=50, verbose_name='Choose your tone')),
                ('voice', models.CharField(choices=[('calm_male', 'Calm Male'), ('soothing_female', 'Soothing Female'), ('gentle_male', 'Gentle Male'), ('warm_female', 'Warm Female'), ('neutral', 'Neutral')], default='calm_male', max_length=50, verbose_name='Choose your voice')),
                ('duration', models.CharField(choices=[('2', '2 min'), ('5', '5 min'), ('10', '10 min'), ('15', '15 min'), ('20', '20 min'), ('30', '30 min')], default='5', max_length=10, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ritual',
                'verbose_name_plural': 'Rituals',
            },
        ),
        migrations.CreateModel(
            name='CustomUserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dream', models.TextField(blank=True, null=True, verbose_name='Tell me about your dream life')),
                ('goals', models.TextField(blank=True, null=True, verbose_name='Specific goals')),
                ('age_range', models.CharField(blank=True, max_length=20, null=True, verbose_name='Age Range')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('happiness', models.TextField(blank=True, null=True, verbose_name='What Makes You Happy?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Detail',
                'verbose_name_plural': 'User Details',
            },
        ),
    ]
