# Generated by Django 5.1.4 on 2025-08-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevicetoken',
            name='app_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='App Version'),
        ),
        migrations.AddField(
            model_name='userdevicetoken',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Model'),
        ),
        migrations.AddField(
            model_name='userdevicetoken',
            name='os_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='OS Version'),
        ),
        migrations.AddField(
            model_name='userdevicetoken',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Platform'),
        ),
    ]
