# Generated by Django 5.1.4 on 2025-08-08 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdevicetoken_app_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdetail',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='customuserdetail',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Interests and Hobbies'),
        ),
        migrations.AddField(
            model_name='customuserdetail',
            name='meditation_experience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Meditation Experience'),
        ),
        migrations.AddField(
            model_name='customuserdetail',
            name='stress_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Current Stress Level'),
        ),
        migrations.AddField(
            model_name='customuserdetail',
            name='sleep_quality',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Sleep Quality'),
        ),
        migrations.AddField(
            model_name='customuserdetail',
            name='preferred_meditation_time',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Preferred Meditation Time'),
        ),
        migrations.AddField(
            model_name='customuserdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuserdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='customuserdetail',
            name='age_range',
            field=models.CharField(blank=True, choices=[('under_18', 'Under 18'), ('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46-55', '46-55'), ('over_55', 'Over 55')], max_length=20, null=True, verbose_name='Age Range'),
        ),
    ]
