# Generated by Django 5.1.4 on 2025-07-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_plans_rituals_customuserdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rituals',
            name='duration',
            field=models.CharField(choices=[('2', '2 min'), ('5', '5 min'), ('10', '10 min')], default='5', max_length=10, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='ritual_type',
            field=models.CharField(choices=[('guided_meditations', 'Guided meditations'), ('story', 'Story')], default='guided_meditations', max_length=50, verbose_name='Ritual Type'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='tone',
            field=models.CharField(choices=[('dreamy', 'Dreamy'), ('asmr', 'ASMR')], max_length=50, verbose_name='Choose your tone'),
        ),
        migrations.AlterField(
            model_name='rituals',
            name='voice',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50, verbose_name='Choose your voice'),
        ),
    ]
