# Generated by Django 5.1.4 on 2025-07-19 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_rituals_duration_alter_rituals_ritual_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RitualType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ritual Type Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Ritual Type',
                'verbose_name_plural': 'Ritual Types',
            },
        ),
        migrations.CreateModel(
            name='MeditationGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='meditations/', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to='accounts.rituals', verbose_name='Ritual')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('ritual_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to='accounts.ritualtype', verbose_name='Ritual Type')),
            ],
            options={
                'verbose_name': 'Meditation',
                'verbose_name_plural': 'Meditations',
            },
        ),
    ]
