# Generated by Django 5.1.4 on 2025-07-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ritualtype_meditationgenerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationgenerate',
            name='custom_user_detail',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meditations', to='accounts.customuserdetail', verbose_name='User Detail'),
            preserve_default=False,
        ),
    ]
