# Generated by Django 5.1.4 on 2025-07-19 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_meditationgenerate_custom_user_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meditationgenerate',
            name='custom_user_detail',
        ),
    ]
