# Generated by Django 5.1.4 on 2025-07-19 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_meditationlibrary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': '1. Users'},
        ),
        migrations.AlterModelOptions(
            name='meditationgenerate',
            options={'verbose_name': 'Meditation', 'verbose_name_plural': '3. Meditations'},
        ),
        migrations.AlterModelOptions(
            name='meditationlibrary',
            options={'verbose_name': 'Meditation Library', 'verbose_name_plural': '4. Meditation Libraries'},
        ),
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'Plan', 'verbose_name_plural': '5. Plans'},
        ),
        migrations.AlterModelOptions(
            name='ritualtype',
            options={'verbose_name': 'Ritual Type', 'verbose_name_plural': '2. Ritual Types'},
        ),
        migrations.RemoveField(
            model_name='plans',
            name='description',
        ),
        migrations.AlterField(
            model_name='meditationgenerate',
            name='details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ritual', to='accounts.rituals', verbose_name='Customize Ritual'),
        ),
        migrations.AlterField(
            model_name='meditationgenerate',
            name='ritual_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ritual_type', to='accounts.ritualtype', verbose_name='Ritual Type'),
        ),
        migrations.CreateModel(
            name='PlanDescriptin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_description', to='accounts.plans', verbose_name='Plan')),
            ],
            options={
                'verbose_name': 'Plan Description',
                'verbose_name_plural': 'Plan Descriptions',
            },
        ),
    ]
