# Generated by Django 5.1.4 on 2025-07-21 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_date', models.DateField(auto_now_add=True, verbose_name='Login Date')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Login Tracker',
                'verbose_name_plural': '6. User Login Trackers',
                'unique_together': {('user', 'login_date')},
            },
        ),
    ]
