# Generated by Django 5.1.4 on 2025-07-21 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userlogintracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMeditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('meditation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_meditation', to='accounts.meditationgenerate', verbose_name='Meditation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_meditation', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Like Meditation',
                'verbose_name_plural': 'Like Meditations',
            },
        ),
        migrations.CreateModel(
            name='UserCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_choice', models.CharField(blank=True, choices=[('struggling', 'Struggling'), ('neutral', 'Neutral'), ('excellent', 'Excellent')], max_length=10, null=True, verbose_name='Check In Choice')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('check_in_date', models.DateField(auto_now_add=True, verbose_name='Check In Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Check In',
                'verbose_name_plural': 'User Check Ins',
            },
        ),
    ]
