# Generated by Django 5.1.4 on 2025-07-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_likemeditation_usercheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationlibrary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meditation_library/', verbose_name='Image'),
        ),
    ]
