# Generated by Django 5.1.4 on 2025-07-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_meditationlibrary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meditationgenerate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
        migrations.AddField(
            model_name='meditationlibrary',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Deleted'),
        ),
    ]
