# Generated by Django 5.1.4 on 2025-07-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_meditationgenerate_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='is_free_trial',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Free Trial'),
        ),
    ]
