# Generated by Django 5.1.4 on 2025-07-31 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLifeVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('vision_type', models.CharField(choices=[('life_vision', 'Life Vision'), ('goal', 'Goal'), ('dream', 'Dream'), ('north_star', 'North Star')], default='life_vision', max_length=20, verbose_name='Vision Type')),
                ('goal_status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('not_started', 'Not Started'), ('paused', 'Paused')], default='not_started', max_length=20, verbose_name='Goal Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is Completed')),
                ('priority', models.IntegerField(default=1, verbose_name='Priority')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target Date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_visions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Life Vision',
                'verbose_name_plural': '7. User Life Visions',
                'ordering': ['-created_at'],
            },
        ),
    ]
